export const DI_TOKENS = {
  APP_CONFIG: Symbol('Config'),
  DB_CLIENT: Symbol('DbClient'),
  MQ_CLIENT: Symbol('MQClient'),
  CACHE_CLIENT: Symbol('CacheClient'),
  USER_REPOSITORY: Symbol('UserRepository'),
  TOKEN_SERVICE: Symbol('ITokenService'),
  REFRESH_TOKEN_CACHE_SERVICE: Symbol('IRefreshTokenCacheService'),
  USER_CACHE_SERVICE: Symbol('IUserCacheService'),
  ACCOUNT_SERVICE: Symbol('IAccountService'),
  NOTIFICATION_SERVICE: Symbol('INotificationService'),
  PASSWORD_RESET_CACHE_SERVICE: Symbol('IPasswordResetCacheService'),
  OAUTH_GOOGLE: Symbol('GoogleOauthProvider'),
  OAUTH_FACEBOOK: Symbol('FacebookOauthProvider'),
  OAUTH_PROVIDER_FACTORY: Symbol('OauthProviderFactory'),
  MQ_SERVICE: Symbol('MQService'),
  CACHE_SERVICE: Symbol('CacheService'),
  AUTH_SERVICE: Symbol('AuthService'),
};
